// pages/index.js
import { useState } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image'
import GLTFViewer2 from '../components/GLTFViewer2';
import GLTFViewer from '../components/GLTFViewer';
import logo from "../public/logo.png"
export default function Home() {
  const [activeComponent, setActiveComponent] = useState('Menu');

  const renderComponent = () => {
    switch (activeComponent) {
      case 'GLTFViewer':
        return <GLTFViewer />;
      case 'GLTFViewer2':
        return <GLTFViewer2 />;
  
      default:
        return <GLTFViewer2 />;
    }
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-[#4F84A0]">
    <Head>
      <title>SAW INDO</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='md:w-1/2 w-full px-1'>
                  <Image src={logo} width={100} height={100} alt="" className=' rounded-3xl mx-auto' />
    </div>
    <div className="absolute top-6 right-1 flex space-x-2 mt-8 mr-8">
      {/* <button
        className="bg-gray-300 px-4 py-2 rounded-md"
        onClick={() => setActiveComponent('GLTFViewer')}
      >
        ANIM 1
      </button> */}
      {/* <Link href="https://linktr.ee/saw_id" passHref>
    <button
        className="bg-[#5d97b6] px-4 py-2 mt-6 rounded-md font-bold text-white"
        // onClick={() => setActiveComponent('GLTFViewer2')}
      >
        ABOUT
      </button>
      </Link> */}
    </div>

    <main className="bg-[#5d97b6] rounded-2xl shadow-lg p-4 w-[80%] h-[20%] relative mt-2">
    <Link href="https://linktr.ee/saw_id" passHref>
    <button
        className="bg-[#5d97b6]  shadow-lg px-4 py-2 top-0 rounded-md font-bold text-white"
        // onClick={() => setActiveComponent('GLTFViewer2')}
      >
        ABOUT
      </button>
      </Link>
      {renderComponent()}
    </main>
  </div>
  );
}
